{
 "title": "Dashboard_for_exp",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "localhost:9100",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "平均温度",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "CPU使用率（%）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[1m]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 1, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "进带宽（in）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"localhost:9100\"}[5m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "出带宽（out）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"localhost:9100\"}[5m])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行线程数",
   "type": "stat",
   "gridPos": { "h": 2.5, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{instance=\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 2.5, "w": 4, "x": 0, "y": 6.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\"} - node_memory_Buffers_bytes{instance=\"localhost:9100\"} - node_memory_Cached_bytes{instance=\"localhost:9100\"}) / (node_memory_MemTotal_bytes{instance=\"localhost:9100\"} )) * 100"
    }
   ]
  }
 ]
}